version: 0.1

phases:
  install:
    commands:
      - cd ~; wget https://raw.github.com/technomancy/leiningen/stable/bin/lein; chmod +x lein; mv lein /bin
      - LEIN_ROOT=true lein
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - LEIN_ROOT=true lein uberjar
      - mv target/lambda-sample-0.1.0-standalone.jar .
      - jar xf lambda-sample-0.1.0-standalone.jar
      - rm -rf target src buildspec.yml project.clj pom.xml lambda-sample-0.1.0-standalone.jar
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.json
artifacts:
  files:
    - template-export.json
