AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Resources:
  SimpleLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: "com.jebbeich.simple::handler"
      Runtime: java8
      MemorySize: 320
      Timeout: 3
      Role: "arn:aws:iam::803068370526:role/simple-lambda-role"
